# Validate this file using http://lint.travis-ci.org/
language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip install --use-mirrors -r requirements.txt
  - python setup.py install
script: nosetests
